# netlify toml configuration
[build]
base = "./"
publish = "./dist/jamesaworo/"
command = "rm package-lock.json &&
           rm -rf node_modules &&
           npm install --save --legacy-peer-deps && ng build"

[functions]
directory = "/netlify/functions/"
external_node_modules = ["mongodb", "netlify"]
