# netlify toml configuration
[build]
base = "./"
publish = "./dist/jamesaworo/"
command = "ng build"

[build.environment]
NPM_FLAGS = "--legacy-peer-deps"


[functions]
    directory = "/netlify/functions/"
    external_node_modules = ["mongodb", "netlify"]
