# netlify toml configuration
[build]
base = "./"
publish = "./dist/jamesaworo/"
command = "npm install --legacy-peer-deps && ng build"

[functions]
directory = "/netlify/functions/"
external_node_modules = ["mongodb", "netlify"]
